### ISSUE TITLE
Add a CONTRIBUTING.md

### ISSUE THREAD

**Issue by andreoav** [alexrochas/web_frameworks-benchmark#1]
Consider adding a CONTRIBUTING.md file that explains the process of adding a new framework to the comparison and how to run benchmarks.

**Comment by alexrochas** [comment]
Really good idea! I will write one.

**Comment by alexrochas** [comment]
There it is! 

How about that [CONTRIBUTING.md](https://github.com/alexrochas/web_frameworks-benchmark/blob/master/CONTRIBUTING.md)?

 :stuck_out_tongue_closed_eyes:
